import React, { useState } from 'react';
import { Bot, X, Minimize2, Maximize2, Send, Sparkles, Code, GraduationCap, Microscope, CheckCircle2 } from 'lucide-react';
import { soundFx } from '../utils/soundEffects';
import { predictSiliconArchitecture } from '../utils/kansenEngine';

interface ShinzuMessage {
  id: string;
  sender: 'user' | 'shinzu';
  text: string;
  timestamp: string;
  mode?: 'STUDENT' | 'SCIENTIST';
  actionExecuted?: string;
}

interface ShinzuCopilotProps {
  onExecuteMacro?: (command: string) => void;
  currentCode?: string;
  currentTitle?: string;
  onUpdateCode?: (newCode: string) => void;
}

export const ShinzuCopilot: React.FC<ShinzuCopilotProps> = ({
  onExecuteMacro,
  currentCode = '',
  currentTitle = 'Active Circuit',
  onUpdateCode
}) => {
  const [isOpen, setIsOpen] = useState(false);
  const [isMinimized, setIsMinimized] = useState(false);
  const [inputText, setInputText] = useState('');
  const [isProcessing, setIsProcessing] = useState(false);
  const [personaMode, setPersonaMode] = useState<'STUDENT' | 'SCIENTIST'>('SCIENTIST');

  const [messages, setMessages] = useState<ShinzuMessage[]>([
    {
      id: '1',
      sender: 'shinzu',
      text: 'SHINZU // QUANTUM SILICON CORE online. Autonomous AI Peer active with VFS read/write clearance and Monaco text buffer injection capabilities.',
      timestamp: new Date().toLocaleTimeString(),
      mode: 'SCIENTIST'
    }
  ]);

  const handleSendMessage = async (textToSend?: string) => {
    const prompt = textToSend || inputText;
    if (!prompt.trim()) return;

    soundFx.playClick();
    const userMsg: ShinzuMessage = {
      id: Date.now().toString(),
      sender: 'user',
      text: prompt,
      timestamp: new Date().toLocaleTimeString()
    };

    setMessages(prev => [...prev, userMsg]);
    if (!textToSend) setInputText('');
    setIsProcessing(true);

    setTimeout(() => {
      let actionTag = '';
      let generatedVerilog = '';

      const cleanPrompt = prompt.toLowerCase();
      if (cleanPrompt.includes('multiplier') || cleanPrompt.includes('8-bit') || cleanPrompt.includes('pipeline')) {
        generatedVerilog = `// Pipelined 8-Bit Multiplier Core Generated by SHINZU AI Peer
module pipelined_multiplier_8bit (
  input wire clk,
  input wire rst_n,
  input wire [7:0] a,
  input wire [7:0] b,
  output reg [15:0] product
);
  reg [15:0] stage1_mult;
  
  always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      stage1_mult <= 16'd0;
      product <= 16'd0;
    end else begin
      stage1_mult <= a * b;
      product <= stage1_mult;
    end
  end
endmodule`;
        if (onUpdateCode) {
          onUpdateCode(generatedVerilog);
          actionTag = 'VFS CODE BUFFER UPDATED: Injected 8-bit Pipelined Multiplier RTL';
        }
      } else if (cleanPrompt.includes('inverter') || cleanPrompt.includes('inv_x1')) {
        generatedVerilog = `// High-Speed 3nm Nanosheet Inverter
module inv_x1_3nm (
  input wire in_a,
  output wire out_y
);
  assign out_y = ~in_a;
endmodule`;
        if (onUpdateCode) {
          onUpdateCode(generatedVerilog);
          actionTag = 'VFS CODE BUFFER UPDATED: Injected High-Speed 3nm Inverter RTL';
        }
      } else if (cleanPrompt.includes('register') || cleanPrompt.includes('dff')) {
        generatedVerilog = `// D-Flip-Flop Register with Asynchronous Reset
module dff_register_3nm (
  input wire clk,
  input wire rst_n,
  input wire data_in,
  output reg data_out
);
  always @(posedge clk or negedge rst_n) begin
    if (!rst_n)
      data_out <= 1'b0;
    else
      data_out <= data_in;
  end
endmodule`;
        if (onUpdateCode) {
          onUpdateCode(generatedVerilog);
          actionTag = 'VFS CODE BUFFER UPDATED: Injected DFF Register RTL';
        }
      }

      let responseText = predictSiliconArchitecture(prompt, { activeModule: currentTitle, userCode: currentCode });

      if (personaMode === 'STUDENT') {
        responseText = `[STUDENT GUIDE MODE] Let's break this down step-by-step:\n\n` +
          `• Concept: Digital logic components like inverters or multipliers route electrical signals between transistors.\n` +
          `• Process Math: Speed is determined by how fast electrons move through thin silicon wires (propagation delay in picoseconds).\n` +
          `• Action Taken: ${actionTag || 'Analyzed code syntax and verified signal paths.'}\n\n` +
          `Tip: Always separate combinational logic (math) from sequential logic (clocked flip-flops) for clean chip design!`;
      } else {
        responseText = `[PRINCIPAL SCIENTIST MODE] Sub-3nm Technology Trade-off Analysis:\n\n` +
          `• PDK Parasitics: GAA Nanosheet sheet resistance (R_sheet = 42Ω/sq) imposes RC interconnect bottlenecks on Metal-1.\n` +
          `• Cleanroom Metrics: ULPA Class-3 Air Changes Per Hour (ACH=500) prevents defect density D0 > 0.08/cm².\n` +
          `• ${responseText}\n` +
          (actionTag ? `\n[AUTONOMOUS VFS DIRECTIVE]: ${actionTag}` : '');
      }

      const shinzuMsg: ShinzuMessage = {
        id: (Date.now() + 1).toString(),
        sender: 'shinzu',
        text: responseText,
        timestamp: new Date().toLocaleTimeString(),
        mode: personaMode,
        actionExecuted: actionTag
      };

      setMessages(prev => [...prev, shinzuMsg]);
      setIsProcessing(false);
      soundFx.playSynthPass();

      if (prompt.startsWith('/') && onExecuteMacro) {
        onExecuteMacro(prompt);
      }
    }, 600);
  };

  if (!isOpen) {
    return (
      <button
        onClick={() => {
          soundFx.playClick();
          setIsOpen(true);
        }}
        className="fixed bottom-4 right-4 z-40 bg-[#000000] border-2 border-[#dc2626] text-white px-3.5 py-2 rounded-full font-orbitron font-bold text-xs flex items-center gap-2 shadow-[0_0_25px_rgba(220,38,38,0.5)] hover:scale-105 transition"
      >
        <Bot className="w-4 h-4 text-[#dc2626] animate-pulse" />
        <span>SHINZU AI PEER</span>
      </button>
    );
  }

  return (
    <div className={`fixed z-40 bg-[#050505] border-2 border-[#dc2626] rounded-lg shadow-[0_0_35px_rgba(220,38,38,0.4)] flex flex-col font-mono text-xs transition-all duration-300 ${
      isMinimized ? 'bottom-4 right-4 w-80 h-12 overflow-hidden' : 'bottom-4 right-4 w-[420px] h-[520px]'
    }`}>
      {/* Copilot Header */}
      <div className="bg-[#000000] border-b border-[#18181b] p-2.5 flex items-center justify-between select-none">
        <div className="flex items-center gap-2">
          <Bot className="w-4 h-4 text-[#dc2626] animate-pulse" />
          <span className="font-orbitron font-bold text-white text-xs tracking-wider">
            SHINZU // AI PEER
          </span>
          <span className="bg-[#dc2626]/20 text-[#dc2626] text-[9px] px-1.5 py-0.5 rounded font-bold border border-[#dc2626]/40">
            VFS ACCESS
          </span>
        </div>

        <div className="flex items-center gap-1">
          <button
            onClick={() => {
              soundFx.playClick();
              setIsMinimized(!isMinimized);
            }}
            className="p-1 hover:bg-zinc-800 text-zinc-400 hover:text-white rounded"
          >
            {isMinimized ? <Maximize2 className="w-3.5 h-3.5" /> : <Minimize2 className="w-3.5 h-3.5" />}
          </button>
          <button
            onClick={() => {
              soundFx.playClick();
              setIsOpen(false);
            }}
            className="p-1 hover:bg-zinc-800 text-zinc-400 hover:text-white rounded"
          >
            <X className="w-3.5 h-3.5" />
          </button>
        </div>
      </div>

      {!isMinimized && (
        <>
          {/* Persona Mode Selector & Quick Prompts */}
          <div className="bg-[#000000] border-b border-[#18181b] p-2 flex items-center justify-between gap-2 text-[10px]">
            <div className="flex items-center gap-1 bg-[#050505] p-1 rounded border border-zinc-800">
              <button
                onClick={() => {
                  soundFx.playClick();
                  setPersonaMode('STUDENT');
                }}
                className={`px-2 py-0.5 rounded flex items-center gap-1 transition ${
                  personaMode === 'STUDENT'
                    ? 'bg-amber-950/80 text-amber-300 font-bold border border-amber-800'
                    : 'text-zinc-500 hover:text-zinc-300'
                }`}
              >
                <GraduationCap className="w-3 h-3" /> STUDENT
              </button>
              <button
                onClick={() => {
                  soundFx.playClick();
                  setPersonaMode('SCIENTIST');
                }}
                className={`px-2 py-0.5 rounded flex items-center gap-1 transition ${
                  personaMode === 'SCIENTIST'
                    ? 'bg-[#dc2626]/30 text-white font-bold border border-[#dc2626]'
                    : 'text-zinc-500 hover:text-zinc-300'
                }`}
              >
                <Microscope className="w-3 h-3 text-[#dc2626]" /> SCIENTIST
              </button>
            </div>

            <div className="flex gap-1 overflow-x-auto">
              <button
                onClick={() => handleSendMessage('Generate optimized pipelined 8-bit multiplier RTL')}
                className="bg-zinc-900 hover:bg-zinc-800 text-white px-2 py-1 rounded border border-zinc-800 shrink-0 font-bold flex items-center gap-1 text-[9px]"
              >
                <Code className="w-3 h-3 text-[#dc2626]" /> Multiplier RTL
              </button>
              <button
                onClick={() => handleSendMessage('/tapeout')}
                className="bg-zinc-900 hover:bg-zinc-800 text-[#dc2626] px-2 py-1 rounded border border-zinc-800 shrink-0 font-bold text-[9px]"
              >
                /tapeout
              </button>
            </div>
          </div>

          {/* Messages Scroll Area */}
          <div className="flex-1 overflow-y-auto p-3 space-y-2 bg-[#000000] leading-relaxed text-[11px]">
            {messages.map((m) => (
              <div
                key={m.id}
                className={`p-2.5 rounded border ${
                  m.sender === 'user'
                    ? 'bg-zinc-900 border-zinc-800 text-zinc-200 ml-6'
                    : 'bg-[#050505] border-[#18181b] text-white mr-2'
                }`}
              >
                <div className="flex justify-between items-center text-[9px] text-zinc-500 font-bold mb-1">
                  <span>{m.sender === 'user' ? 'OPERATIVE' : `SHINZU [${m.mode || personaMode}]`}</span>
                  <span>{m.timestamp}</span>
                </div>
                <p className="whitespace-pre-wrap">{m.text}</p>
                {m.actionExecuted && (
                  <div className="mt-2 p-1.5 bg-emerald-950/40 border border-emerald-800 rounded text-emerald-400 font-bold text-[9px] flex items-center gap-1.5">
                    <CheckCircle2 className="w-3.5 h-3.5 shrink-0" />
                    <span>{m.actionExecuted}</span>
                  </div>
                )}
              </div>
            ))}
            {isProcessing && (
              <div className="text-[10px] text-[#dc2626] italic animate-pulse p-1 flex items-center gap-2">
                <Sparkles className="w-3 h-3 animate-spin" />
                SHINZU EXECUTING VFS COMPILATION MATRIX...
              </div>
            )}
          </div>

          {/* Input Bar */}
          <div className="p-2 bg-[#000000] border-t border-[#18181b] flex items-center gap-1.5">
            <input
              type="text"
              value={inputText}
              onChange={(e) => setInputText(e.target.value)}
              onKeyDown={(e) => e.key === 'Enter' && handleSendMessage()}
              placeholder="Dictate RTL synthesis, VFS edits, or layout queries..."
              className="flex-1 bg-[#050505] text-white placeholder-zinc-600 px-2.5 py-1.5 rounded border border-[#18181b] focus:outline-none focus:border-[#dc2626] font-mono text-xs"
            />
            <button
              onClick={() => handleSendMessage()}
              className="p-1.5 bg-[#dc2626] hover:bg-[#b91c1c] text-white rounded transition border border-[#dc2626]"
            >
              <Send className="w-3.5 h-3.5" />
            </button>
          </div>
        </>
      )}
    </div>
  );
};
